// controller/statsController.js

const db = require('../config/db'); // mysql2 pool/connection

const getSummaryStats = async (req, res) => {
  try {
    // Count all workers
    const [workersCount] = await db.query("SELECT COUNT(*) AS totalWorkers FROM information");

    // Count IDs generated today
    const [idsRows] = await db.query(`
      SELECT COUNT(*) AS idsGeneratedToday 
      FROM information 
      WHERE DATE(created_at) = CURDATE()
    `);

    // Count IDs generated by month
    const [idsByMonth] = await db.query(`
      SELECT COUNT(*) AS idsGeneratedByMonth
      FROM information
      WHERE MONTH(created_at) = MONTH(CURDATE()) AND YEAR(created_at) = YEAR(CURDATE())
    `);

    // Count total departments
    const [departmentsCount] = await db.query(`
      SELECT COUNT(DISTINCT department) AS totalDepartments
      FROM information
    `);

    res.json({
      totalWorkers: workersCount[0].totalWorkers,
      idsGeneratedToday: idsRows[0].idsGeneratedToday,
      idsGeneratedByMonth: idsByMonth[0].idsGeneratedByMonth,
      totalDepartments: departmentsCount[0].totalDepartments
    });
  } catch (err) {
    console.error("Error fetching stats:", err);
    res.status(500).json({ error: "Failed to fetch summary statistics" });
  }
};

module.exports = getSummaryStats;